### ISSUE TITLE
building in separate directory

### ISSUE THREAD

**Issue by veggiesaurus** [Starlink/ast#15]
Running configure from a separate folder (and using --disable-fortran, although this might occur even with fortran) causes an error, because makeh and ast_par.source are not in the build directory, but rather in the source directory.

I solved this issue manually by copying `makeh` and `ast_par.source` to the build directory, but this should probably be fixed in the build configuration.

Related: should `ast_par.source` be required at all if running with `--disable-fortran`?

**Comment by dsberry** [comment]
I'm not entirely sure what you mean by "running configure from a separate folder". Are you using a clone of the git repo or a release tar file? If its a clone of the git repo you presumably do

% cd ast
% ./bootstrap

first. Do you mean you then go to another directory for the rest - like:

% cd ../newdir
% ../ast/configure
% make

Or am I misunderstanding you?

BTW - you're right that AST_PAR et al are not needed if fortran is disabled. I've modified Makefile.am appropriately

David

**Comment by veggiesaurus** [comment]
@dsberry here's an example (assuming ast-9.2.3.tar.gz is extracted to`~/source/ast-9.2.3`)

```
mkdir -p ~/build/ast_build
cd ~/build/ast_build
../../source/ast-9.2.3/configure --without-fortran
make
```


Everything is fine until
```
Can't open perl script "./makeh": No such file or directory
make[1]: *** [Makefile:4489: ast.h] Error 2
```

If I run `make` again, I then get another error due to `ast_par.source` also missing from the build directory, although I imagine the latest commits you made will sort that out.

The `makeh` occurs on both Linux and Windows, though.

**Comment by dsberry** [comment]
@veggiesaurus I've pushed a change to Makefile.am that should fix this. Do you need a new release now or could it wait until I have some more changes ready for release?

**Comment by veggiesaurus** [comment]
> @veggiesaurus I've pushed a change to Makefile.am that should fix this. Do you need a new release now or could it wait until I have some more changes ready for release?

I was hoping for a new release so that I could remove the patches from my vcpkg portfile PR. But that in itself is not urgent, so it could wait until you have more changes if it's a hassle.

**Comment by dsberry** [comment]
@veggiesaurus  I've made release v9.2.4 today, which includes these changes.
