### ISSUE TITLE
ast fails to build in macOS-11 MacPorts environment

### ISSUE THREAD

**Issue by JohnPritchard** [Starlink/ast#16]
Although I can successfully build ast-9.2.4 with a simple:

`curl -O https://github.com/Starlink/ast/releases/download/v9.2.4/ast-9.2.4.tar.gz`
`tar -zxf ast-9.2.4.tar.gz`
`cd ast-9.2.4`
`./confiure`
`make`

It fails to build in a MacPorts build environment in a macOS-11.4 + Xcode-12.5 environment. (In general, the "MacPorts build environment" is _stricter_ than a "normal" one, and thus catches coding errors that otherwise are perhaps only warnings in a "normal" environment.)

The currently supported ast version in the official MacPorts repository is 9.0.1, but even if I update the Portfile to use 9.2.4, I get the same set of errors, which is:

>libtool: link: /usr/bin/clang -dynamiclib  -o .libs/libast.9.dylib  src/.libs/libast_la-yamlchan.o src/.libs/libast_la-axis.o src/.libs/libast_la-box.o src/.libs/libast_la-channel.o src/.libs/libast_la-chebymap.o src/.libs/libast_la-circle.o src/.libs/libast_la-cmpframe.o src/.libs/libast_la-cmpmap.o src/.libs/libast_la-cmpregion.o src/.libs/libast_la-dsbspecframe.o src/.libs/libast_la-dssmap.o src/.libs/libast_la-ellipse.o src/.libs/libast_la-error.o src/.libs/libast_la-fitschan.o src/.libs/libast_la-fitstable.o src/.libs/libast_la-fluxframe.o src/.libs/libast_la-frame.o src/.libs/libast_la-frameset.o src/.libs/libast_la-globals.o src/.libs/libast_la-grismmap.o src/.libs/libast_la-interval.o src/.libs/libast_la-intramap.o src/.libs/libast_la-keymap.o src/.libs/libast_la-loader.o src/.libs/libast_la-lutmap.o src/.libs/libast_la-mapping.o src/.libs/libast_la-mathmap.o src/.libs/libast_la-matrixmap.o src/.libs/libast_la-memory.o src/.libs/libast_la-moc.o src/.libs/libast_la-mocchan.o src/.libs/libast_la-normmap.o src/.libs/libast_la-nullregion.o src/.libs/libast_la-object.o src/.libs/libast_la-pcdmap.o src/.libs/libast_la-permmap.o src/.libs/libast_la-plot.o src/.libs/libast_la-plot3d.o src/.libs/libast_la-pointlist.o src/.libs/libast_la-pointset.o src/.libs/libast_la-polygon.o src/.libs/libast_la-polymap.o src/.libs/libast_la-prism.o src/.libs/libast_la-ratemap.o src/.libs/libast_la-region.o src/.libs/libast_la-selectormap.o src/.libs/libast_la-shiftmap.o src/.libs/libast_la-skyaxis.o src/.libs/libast_la-skyframe.o src/.libs/libast_la-slamap.o src/.libs/libast_la-specfluxframe.o src/.libs/libast_la-specframe.o src/.libs/libast_la-specmap.o src/.libs/libast_la-sphmap.o src/.libs/libast_la-stc.o src/.libs/libast_la-stccatalogentrylocation.o src/.libs/libast_la-stcobsdatalocation.o src/.libs/libast_la-stcresourceprofile.o src/.libs/libast_la-stcschan.o src/.libs/libast_la-stcsearchlocation.o src/.libs/libast_la-switchmap.o src/.libs/libast_la-table.o src/.libs/libast_la-timeframe.o src/.libs/libast_la-timemap.o src/.libs/libast_la-tranmap.o src/.libs/libast_la-unit.o src/.libs/libast_la-unitmap.o src/.libs/libast_la-unitnormmap.o src/.libs/libast_la-wcsmap.o src/.libs/libast_la-winmap.o src/.libs/libast_la-xml.o src/.libs/libast_la-xmlchan.o src/.libs/libast_la-xphmap.o src/.libs/libast_la-zoommap.o src/.libs/libast_la-fyamlchan.o src/.libs/libast_la-c2f77.o src/.libs/libast_la-fbox.o src/.libs/libast_la-fchannel.o src/.libs/libast_la-fchebymap.o src/.libs/libast_la-fcircle.o src/.libs/libast_la-fcmpframe.o src/.libs/libast_la-fcmpmap.o src/.libs/libast_la-fcmpregion.o src/.libs/libast_la-fdsbspecframe.o src/.libs/libast_la-fdssmap.o src/.libs/libast_la-fellipse.o src/.libs/libast_la-ferror.o src/.libs/libast_la-ffitschan.o src/.libs/libast_la-ffitstable.o src/.libs/libast_la-ffluxframe.o src/.libs/libast_la-fframe.o src/.libs/libast_la-fframeset.o src/.libs/libast_la-fgrismmap.o src/.libs/libast_la-finterval.o src/.libs/libast_la-fintramap.o src/.libs/libast_la-fkeymap.o src/.libs/libast_la-flutmap.o src/.libs/libast_la-fmapping.o src/.libs/libast_la-fmathmap.o src/.libs/libast_la-fmatrixmap.o src/.libs/libast_la-fmoc.o src/.libs/libast_la-fmocchan.o src/.libs/libast_la-fnormmap.o src/.libs/libast_la-fnullregion.o src/.libs/libast_la-fobject.o src/.libs/libast_la-fpcdmap.o src/.libs/libast_la-fpermmap.o src/.libs/libast_la-fplot.o src/.libs/libast_la-fplot3d.o src/.libs/libast_la-fpointlist.o src/.libs/libast_la-fpolygon.o src/.libs/libast_la-fpolymap.o src/.libs/libast_la-fprism.o src/.libs/libast_la-fratemap.o src/.libs/libast_la-fregion.o src/.libs/libast_la-fselectormap.o src/.libs/libast_la-fshiftmap.o src/.libs/libast_la-fskyframe.o src/.libs/libast_la-fslamap.o src/.libs/libast_la-fspecfluxframe.o src/.libs/libast_la-fspecframe.o src/.libs/libast_la-fspecmap.o src/.libs/libast_la-fsphmap.o src/.libs/libast_la-fstc.o src/.libs/libast_la-fstccatalogentrylocation.o src/.libs/libast_la-fstcobsdatalocation.o src/.libs/libast_la-fstcresourceprofile.o src/.libs/libast_la-fstcschan.o src/.libs/libast_la-fstcsearchlocation.o src/.libs/libast_la-fswitchmap.o src/.libs/libast_la-ftable.o src/.libs/libast_la-ftimeframe.o src/.libs/libast_la-ftimemap.o src/.libs/libast_la-ftranmap.o src/.libs/libast_la-funitmap.o src/.libs/libast_la-funitnormmap.o src/.libs/libast_la-fwcsmap.o src/.libs/libast_la-fwinmap.o src/.libs/libast_la-fxmlchan.o src/.libs/libast_la-fzoommap.o cminpack/.libs/libast_la-lmder1.o cminpack/.libs/libast_la-lmder.o cminpack/.libs/libast_la-dpmpar.o cminpack/.libs/libast_la-enorm.o cminpack/.libs/libast_la-qrfac.o cminpack/.libs/libast_la-lmpar.o cminpack/.libs/libast_la-qrsolv.o wcslib/.libs/libast_la-proj.o wcslib/.libs/libast_la-tpn.o wcslib/.libs/libast_la-wcstrig.o   -L/stardev/git/starlink/star/lib -L/opt/local/lib ./.libs/libast_pal.dylib -lyaml -lpthread  -Os -arch x86_64 -Wl,-headerpad_max_install_names -Wl,-syslibroot -Wl,/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk -arch x86_64   -install_name  /opt/local/lib/libast.9.dylib -compatibility_version 12 -current_version 12.4 -Wl,-single_module
> Undefined symbols for architecture x86_64:
>   "_astG3DAttr", referenced from:
>       _Attr3D in libast_la-plot3d.o
>       _Plot3DAttr in libast_la-plot3d.o
>   "_astG3DCap", referenced from:
>       _Plot3DCap in libast_la-plot3d.o
>   "_astG3DFlush", referenced from:
>       _Plot3DFlush in libast_la-plot3d.o
>   "_astG3DLine", referenced from:
>       _Border in libast_la-plot3d.o
>       _Plot3DLine in libast_la-plot3d.o
>   "_astG3DMark", referenced from:
>       _Mark in libast_la-plot3d.o
>       _Plot3DMark in libast_la-plot3d.o
>   "_astG3DQch", referenced from:
>       _Plot3DQch in libast_la-plot3d.o
>   "_astG3DText", referenced from:
>       _Text in libast_la-plot3d.o
>       _Plot3DText in libast_la-plot3d.o
>   "_astG3DTxExt", referenced from:
>       _Plot3DTxExt in libast_la-plot3d.o
>   "_astGAttr", referenced from:
>       _GAttr in libast_la-plot.o
>   "_astGBBuf", referenced from:
>       _BBuf in libast_la-plot.o
>   "_astGCap", referenced from:
>       _GCap in libast_la-plot.o
>   "_astGEBuf", referenced from:
>       _EBuf in libast_la-plot.o
>   "_astGLine", referenced from:
>       _GLine in libast_la-plot.o
>   "_astGMark", referenced from:
>       _Mark in libast_la-plot.o
>   "_astGQch", referenced from:
>       _DrawText in libast_la-plot.o
>   "_astGScales", referenced from:
>       _GScales in libast_la-plot.o
>   "_astGText", referenced from:
>       _GText in libast_la-plot.o
>   "_astGTxExt", referenced from:
>       _GTxExt in libast_la-plot.o
>   "_astPutErr_", referenced from:
>       _PutErr in libast_la-error.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[1]: *** [libast.la] Error 1
> make[1]: Leaving directory `/opt/local/var/macports/build/_private_tmp_vjpd-ast/ast/work/ast-9.2.4'
> make: *** [all] Error 2

I can make MOST of these missing symbols go away by adding the following objects to the list to be included in the library:

```
   src/.libs/libast_drama_la-err_drama.o
   src/.libs/libast_grf3d_la-grf3d.o
   src/.libs/libast_grf_2_0_la-grf_2.0.o
   src/.libs/libast_grf_5_6_la-grf_5.6.o
   src/.libs/libast_grf_3_2_la-grf_3.2.o
```
However these objects only exist if make is invoked with (8) parallel jobs. If I invoke with no make parallelisation then these objects do not exist at the time the above library is being made.

But even when they do exist and are all added to the above compile command, I then still get the following error:

> Undefined symbols for architecture x86_64:
>   "_ErsRep", referenced from:
>       _astPutErr_ in libast_drama_la-err_drama.o
> ld: symbol(s) not found for architecture x86_64

I can't find an object with a _ErsRep definition. Maybe it's a question of ordering and dependency...

So I think there are some missing dependency definitions that mean all the required objects are not built nor included at the moment that they are required for building the library(ies).

Any chance this can be fixed?

**Comment by timj** [comment]
The AST build system supports run time resolution of symbols. When you link against AST using `ast_link` the arguments to that specify which graphics plugin or error message reporting system are going to be used by your application. This means that when `libast` is built it should not try to do symbol resolution at library creation time. When we build it on mac we always build that way and that's what the configure script should be doing.

AST has successfully been built on Apple Silicon on conda-forge although there are some local patches there that have not been migrated back upstream. See conda-forge/starlink-ast-feedstock#15

I'm not sure what's going wrong with the 9.2.4 build on conda-forge at conda-forge/starlink-ast-feedstock#16

**Comment by JohnPritchard** [comment]
Hi @timj,
Thanks for the quick feedback. Implementing the same patch to configure (i.e. updating the macOS version cases to include 11.*, line 7728) which then means the appropriate linker options are set, solves the build issue for my case, macOS 11.4 on x86_64 (not yet arm64).
So yes it would be great if this could be implemented in the source.
Many thanks in advance.
best regards
John

**Comment by dsberry** [comment]
@JohnPritchard  I've now incorporated the patches from @timj  into the Starlink build system, which is used to create the configure script in the AST source release.
