### ISSUE TITLE
v9.2.10 release tarball

### ISSUE THREAD

**Issue by dg0yt** [Starlink/ast#21]
There is a tag for v9.2.10, https://github.com/Starlink/ast/releases/tag/v9.2.10.
If this is meant to be officially released, can you please create a GH release and add a release tarball as a proper GH asset (as in 9.2.8, not as in 9.2.9)? This would simplify packaging, in particular given the fact that e a stock autoconf isn't enough.

**Comment by dsberry** [comment]
@grahambell - Graham, do you want to make the release (assuming a release is appropriate) or do you want me to do it - I think I can still remember how to do it....

**Comment by grahambell** [comment]
You could do that if you like?  I'm not sure how it was done before.

**Comment by dg0yt** [comment]
The missing compatibility with standard autoconf is a real barrier. Today I found that the included libtool (2.4.2) is outdated.

**Comment by dsberry** [comment]
I've just made a release for v9.2.10 as a GH asset. Sorry for the delay. 

Making changes to the build and installation system is probably beyond my available resources at the moment.
