### ISSUE TITLE
PM_STACK_MAXSIZE gets exceeded easily in a multi-threaded environment

### ISSUE THREAD

**Issue by jvo203** [Starlink/ast#24]
As part of "due diligence", evaluating Starlink AST to see if it can be adopted server-side by our FITSWEBQLSE, I've run into a problem when running a multi-threaded test program:

> astBeginPM: Maximum stack size has been exceeded (internal AST programming error).

Using a small number of threads (i.e. 32) is fine
```
chris@capricorn:~/projects/FITSWEBQLSE/tests> ./test_starlink 10 32
Testing Starlink AST for 10 seconds using 32 threads.
All Starlink AST threads terminated
astFlushMemory: All AST memory blocks were released correctly.
```
Increasing the number of threads to, say, 64 or 128 often (not always but in most cases) results in memory errors. The `PM_STACK_MAXSIZE` of 20 seems to be getting exceeded rather too easily, despite there being only a one level of depth in perfectly matching `astBegin` and `astEnd` calls:
```
chris@capricorn:~/projects/FITSWEBQLSE/tests> ./test_starlink 10 64
Testing Starlink AST for 10 seconds using 64 threads.
!! AST: Error in routine test_fk4 at line 23 in file test_starlink.c.
!  astBeginPM: Maximum stack size has been exceeded (internal AST programming error).
!! astBeginPM: Maximum stack size has been exceeded (internal AST programming error).
!! AST: Error in routine test_fk4 at line 23 in file test_starlink.c.
!  astBeginPM: Maximum stack size has been exceeded (internal AST programming error).
!! AST: Error in routine test_fk4 at line 23 in file test_starlink.c.
!  astBeginPM: Maximum stack size has been exceeded (internal AST programming error).
!  astTimeFrame: Inappropriate units (d) specified for a (null) axis.
!! AST: Error in routine test_fk4 at line 23 in file test_starlink.c.
!  astBeginPM: Maximum stack size has been exceeded (internal AST programming error).
!! AST: Error in routine test_fk4 at line 22 in file test_starlink.c.
!  astBeginPM: Maximum stack size has been exceeded (internal AST programming error).
!! AST: Error in routine test_fk4 at line 23 in file test_starlink.c.
!  astBeginPM: Maximum stack size has been exceeded (internal AST programming error).
!! AST: Error in routine test_fk4 at line 23 in file test_starlink.c.
!  astBeginPM: Maximum stack size has been exceeded (internal AST programming error).
!! AST: Error in routine test_fk4 at line 23 in file test_starlink.c.
!  astEndPM: astEndPM called without matching astBeginPM (internal AST programming error).
!! AST: Error in routine test_fk4 at line 23 in file test_starlink.c.
!  astEndPM: astEndPM called without matching astBeginPM (internal AST programming error).
!! AST: Error in routine test_fk4 at line 23 in file test_starlink.c.
!  astEndPM: astEndPM called without matching astBeginPM (internal AST programming error).
!! AST: Error in routine test_fk4 at line 23 in file test_starlink.c.
!  astEndPM: astEndPM called without matching astBeginPM (internal AST programming error).
!! AST: Error in routine test_fk4 at line 23 in file test_starlink.c.
!  astEndPM: astEndPM called without matching astBeginPM (internal AST programming error).
!! AST: Error in routine test_fk4 at line 22 in file test_starlink.c.
!  astEndPM: astEndPM called without matching astBeginPM (internal AST programming error).
!! AST: Error in routine test_fk4 at line 39 in file test_starlink.c.
!  astEnd: Invalid use of astEnd without a matching astBegin.
!! AST: Error in routine test_fk4 at line 23 in file test_starlink.c.
!  astEndPM: astEndPM called without matching astBeginPM (internal AST programming error).
All Starlink AST threads terminated
!! AST: Error in routine main at line 134 in file test_starlink.c.
!  astFlushMemory: 1 AST memory blocks have not been released (programming error).
```

The AST documentation (inside memory.c) states

> *     Matching pairs of astBeginPM/astEndPM calls can be nested up to a
> *     maximum depth of 20.

yet my test code definitely does not use any nesting (the level is 1).

The existence of hard limits such as `PM_STACK_MAXSIZE` makes me somewhat wary of using AST in a 24-hour multi-threaded server environment as it is difficult to anticipate in advance if / when any internal hard-coded AST limits might get exceeded. There might be other similar hard limits that Starlink AST end-users might not be aware of ... Do you think this is something that the AST project might improve in the near future?

Compile command: `cc  `pkg-config --cflags cfitsio` -o test_starlink test_starlink.c -L/usr/local/lib `ast_link` -pthread`
AST has been configured / compiled with `./configure --prefix=/usr/local --with-memdebug`
Test source code: `test_starlink.c`
[test_starlink.c.txt](https://github.com/user-attachments/files/15756875/test_starlink.c.txt)

**Comment by dsberry** [comment]
I can take a look at this but not until 22nd June. Away on holiday at the moment.

**Comment by jvo203** [comment]
No worries!

**Comment by dsberry** [comment]
I've just pushed a commit that should fix this. It guards against different threads trying to allocate permanent memory blocks simultaneously, resulting in the astBeginPM stack being filled rapidly with a value for each thread, rather than a value for each depth of nesting. Access to the astBeginPM statck is now serialised using a mutex, with each thread keeping a record of its own depth of nesting so that the mutex can be locked and unlocked just by the top level.

**Comment by jvo203** [comment]
Thank you, a silly question but how does one build ast that has been cloned directly from GitHub? The ast releases contain "configure", which the raw GitHub version does not. It contains "bootstrap" instead, which is not found in the normal ast releases. Attempting to run bootstrap results in an error:
```
chris@capricorn:~/projects/ast> ./bootstrap
Bootstrapping /home/chris/projects/ast ...
bootstrap error: The starconf application is not in your path
```

**Comment by dsberry** [comment]
I've created a new release 9.2.11, which is available under "Releases" on the AST github main page.

**Comment by jvo203** [comment]
Many thanks, confirmed as fixed.
