### ISSUE TITLE
tick artifact when using very large line width

### ISSUE THREAD

**Issue by duidae** [Starlink/ast#4]
hi:
currently we are using AST for rendering coordinate systems, really a great library, thanks for your effort! However we met a problem which is the tick artifact when using very large line width. I  wonder why  is there a strange triangle after the rectangular tick?  Hope there could be a fix for this, thanks again!

![ticks](https://user-images.githubusercontent.com/25971696/55056448-1abc1000-50a1-11e9-9922-287b7313ced2.png)

**Comment by dsberry** [comment]
That looks very much like it may be a problem in the Grf module that AST uses for drawing its primitive graphics (see "Choosing a Graphics Package"  http://www.starlink.ac.uk/docs/sun211.htx/sun211se21.html#x22-21100015). Are you using a standard Grf module or have you written your own?

**Comment by duidae** [comment]
wow thanks for the feedback! I'll check it first, thanks again!

**Comment by duidae** [comment]
hi @dsberry we found the problem & it's actually caused by our customized grf function, so really appreciate your help! thank you & ast library again!
